In [1]:
import pandas as pd
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.metrics import balanced_accuracy_score, confusion_matrix, classification_report, roc_auc_score, accuracy_score
import mlflow
import mlflow.sklearn
from sklearn.metrics import roc_auc_score

# Set up MLflow experiment
mlflow.set_experiment("Credit_Risk_Classification_Logistic_Regression")

print("MLflow experiment initialized: Credit_Risk_Classification_Logistic_Regression")
print(f"MLflow tracking URI: {mlflow.get_tracking_uri()}")
print(f"MLflow experiment ID: {mlflow.get_experiment_by_name('Credit_Risk_Classification_Logistic_Regression').experiment_id}")

2025/08/14 10:42:09 INFO mlflow.tracking.fluent: Experiment with name 'Credit_Risk_Classification_Logistic_Regression' does not exist. Creating a new experiment.

MLflow experiment initialized: Credit_Risk_Classification_Logistic_Regression
MLflow tracking URI: file:///Users/nishaantsoni/Documents/My_Projects/Credit_Risk_Classification_using_Logistic_Regression/mlruns
MLflow experiment ID: 259187339359411637

---

## Split the Data into Training and Testing Sets

### Step 1: Read the `lending_data.csv` data from the `Resources` folder into a Pandas DataFrame.

In [2]:
# Read the CSV file from the Resources folder into a Pandas DataFrame
df = pd.read_csv("Resources/lending_data.csv")
df.head()

,loan_size,interest_rate,borrower_income,debt_to_income,num_of_accounts,derogatory_marks,total_debt,loan_status
0,10700.0,7.672,52800,0.431818,5,1,22800,0
1,8400.0,6.692,43600,0.311927,3,0,13600,0
2,9000.0,6.963,46100,0.349241,3,0,16100,0
3,10700.0,7.664,52700,0.430740,5,1,22700,0
4,10800.0,7.698,53000,0.433962,5,1,23000,0

### Step 2: Create the labels set (`y`)  from the “loan_status” column, and then create the features (`X`) DataFrame from the remaining columns.

In [3]:
# Separate the data into labels and features
y = df['loan_status']
X = df.drop(columns='loan_status')

In [4]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: loan_status, dtype: int64

In [5]:
X.head()

,loan_size,interest_rate,borrower_income,debt_to_income,num_of_accounts,derogatory_marks,total_debt
0,10700.0,7.672,52800,0.431818,5,1,22800
1,8400.0,6.692,43600,0.311927,3,0,13600
2,9000.0,6.963,46100,0.349241,3,0,16100
3,10700.0,7.664,52700,0.430740,5,1,22700
4,10800.0,7.698,53000,0.433962,5,1,23000

### Step 3: Check the balance of the labels variable (`y`) by using the `value_counts` function.

In [6]:
# Check the balance of our target values
y.value_counts()

loan_status
0    75036
1     2500
Name: count, dtype: int64

### Step 4: Split the data into training and testing datasets by using `train_test_split`.

In [7]:
from sklearn.model_selection import train_test_split

# Split the data using train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

---

## Create a Logistic Regression Model with the Original Data

###  Step 1: Fit a logistic regression model by using the training data (`X_train` and `y_train`).

In [8]:
from sklearn.linear_model import LogisticRegression

# Instantiate the Logistic Regression model
classifier = LogisticRegression(solver='lbfgs',
                                max_iter=200,
                                random_state=1)
classifier

LogisticRegression(max_iter=200, random_state=1)

In [9]:
# Full MLflow run for original (imbalanced) data logistic regression model
with mlflow.start_run(run_name="Logistic_Regression_Original_Data"):
    from sklearn.linear_model import LogisticRegression
    import tempfile, os

    # Train model
    lr_original = LogisticRegression(solver='lbfgs', max_iter=200, random_state=1)
    lr_original.fit(X_train, y_train)

    # Predictions
    y_train_pred = lr_original.predict(X_train)
    y_test_pred = lr_original.predict(X_test)

    # Metrics
    train_accuracy = accuracy_score(y_train, y_train_pred)
    test_accuracy = accuracy_score(y_test, y_test_pred)
    train_roc_auc = roc_auc_score(y_train, lr_original.predict_proba(X_train)[:, 1])
    test_roc_auc = roc_auc_score(y_test, lr_original.predict_proba(X_test)[:, 1])

    # Classification reports
    train_report = classification_report(y_train, y_train_pred)
    test_report = classification_report(y_test, y_test_pred)

    # Confusion matrices
    train_cm = confusion_matrix(y_train, y_train_pred)
    test_cm = confusion_matrix(y_test, y_test_pred)

    # Log params
    mlflow.log_params({
        "model_type": "LogisticRegression",
        "solver": "lbfgs",
        "C": 1.0,
        "max_iter": 200,
        "random_state": 1,
        "data_type": "original_imbalanced",
        "class_balance": f"healthy: {(y_train == 0).sum()}, high_risk: {(y_train == 1).sum()}",
        "training_samples": len(X_train),
        "features": X_train.shape[1]
    })

    # Log metrics
    mlflow.log_metrics({
        "train_accuracy": train_accuracy,
        "test_accuracy": test_accuracy,
        "train_roc_auc": train_roc_auc,
        "test_roc_auc": test_roc_auc
    })

    # Artifact (evaluation summary)
    with tempfile.NamedTemporaryFile(mode='w', suffix='.txt', delete=False) as f:
        f.write("ORIGINAL DATA MODEL EVALUATION\n")
        f.write("="*50 + "\n\n")
        f.write("TRAIN CONFUSION MATRIX:\n" + str(train_cm) + "\n\n")
        f.write("TEST CONFUSION MATRIX:\n" + str(test_cm) + "\n\n")
        f.write("TRAIN CLASSIFICATION REPORT:\n" + train_report + "\n\n")
        f.write("TEST CLASSIFICATION REPORT:\n" + test_report + "\n")
        eval_file = f.name
    mlflow.log_artifact(eval_file, artifact_path="model_evaluation")
    os.unlink(eval_file)

    # Log model
    mlflow.sklearn.log_model(lr_original, "logistic_regression_original_model")

    print("✅ Original data model trained & fully logged to MLflow")
    print(f"Test Accuracy: {test_accuracy:.4f} | Test ROC AUC: {test_roc_auc:.4f}")

2025/08/14 10:42:09 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/08/14 10:42:12 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/08/14 10:42:12 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

✅ Original data model trained & fully logged to MLflow
Test Accuracy: 0.9926 | Test ROC AUC: 0.9939

### Step 2: Save the predictions on the testing data labels by using the testing feature data (`X_test`) and the fitted model.

In [10]:
# (Removed) Predictions handled inside consolidated MLflow run above.
print("Predictions and metrics logged within the MLflow run block.")

Predictions and metrics logged within the MLflow run block.

### Step 3: Evaluate the model’s performance by doing the following:

* Calculate the accuracy score of the model.

* Generate a confusion matrix.

* Print the classification report.

In [11]:
# Accuracy already computed & logged to MLflow inside consolidated run.
print("Accuracy logged to MLflow; view via mlflow ui.")

Accuracy logged to MLflow; view via mlflow ui.

In [12]:
training_matrix = confusion_matrix(y_train, y_train_pred)
print(training_matrix)

[[55988   283]
 [  137  1744]]

In [13]:
testing_matrix = confusion_matrix(y_test, y_test_pred)
print(testing_matrix)

[[18658   107]
 [   37   582]]

In [14]:
training_report = classification_report(y_train, y_train_pred)
print(training_report)

              precision    recall  f1-score   support

           0       1.00      0.99      1.00     56271
           1       0.86      0.93      0.89      1881

    accuracy                           0.99     58152
   macro avg       0.93      0.96      0.94     58152
weighted avg       0.99      0.99      0.99     58152

In [15]:
# Print the Testing classification report for the model
testing_report = classification_report(y_test, y_test_pred)
print(testing_report)

# Continue the MLflow run to log metrics and artifacts
# Calculate additional metrics for logging
test_accuracy = accuracy_score(y_test, y_test_pred)
train_accuracy = accuracy_score(y_train, y_train_pred)

# Calculate ROC AUC
test_roc_auc = roc_auc_score(y_test, lr_original.predict_proba(X_test)[:, 1])
train_roc_auc = roc_auc_score(y_train, lr_original.predict_proba(X_train)[:, 1])

# Log metrics to MLflow
mlflow.log_metrics({
    "test_accuracy": test_accuracy,
    "train_accuracy": train_accuracy,
    "test_roc_auc": test_roc_auc,
    "train_roc_auc": train_roc_auc
})

# Log confusion matrix as text artifact
import tempfile
import os

with tempfile.NamedTemporaryFile(mode='w', suffix='.txt', delete=False) as f:
    f.write("TRAINING CONFUSION MATRIX:\n")
    f.write(str(training_matrix))
    f.write("\n\nTESTING CONFUSION MATRIX:\n")
    f.write(str(testing_matrix))
    f.write("\n\nCLASSIFICATION REPORT:\n")
    f.write(testing_report)
    temp_file = f.name

mlflow.log_artifact(temp_file, "model_evaluation")
os.unlink(temp_file)

# Log the model
mlflow.sklearn.log_model(lr_original, "logistic_regression_model")

print("✅ Metrics, artifacts, and model logged to MLflow")

2025/08/14 10:42:12 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

              precision    recall  f1-score   support

           0       1.00      0.99      1.00     18765
           1       0.84      0.94      0.89       619

    accuracy                           0.99     19384
   macro avg       0.92      0.97      0.94     19384
weighted avg       0.99      0.99      0.99     19384

2025/08/14 10:42:13 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

✅ Metrics, artifacts, and model logged to MLflow

### Step 4: Answer the following question.

**Question:** How well does the logistic regression model predict both the `0` (healthy loan) and `1` (high-risk loan) labels?

**Answer:** The Logistic Regression model does very well at predicting healthy loans with accuracy, precision and recall close to 100%. It still does well, but performs noticably worse at identifying high-risk loans where it has a precision of 84% and a recall of 94%. This suggests that this model is less able to classify high risk loans than healthy loans. This is likely related to the skew in the data that was provided, with only about 3 percent of the sample being in the high risk loans category.

---

## Predict a Logistic Regression Model with Resampled Training Data

### Step 1: Use the `RandomOverSampler` module from the imbalanced-learn library to resample the data. Be sure to confirm that the labels have an equal number of data points.

In [16]:
# Import the RandomOverSampler module form imbalanced-learn
from imblearn.over_sampling import RandomOverSampler

ROS = RandomOverSampler(random_state=1)

X_resampled, y_resampled= ROS.fit_resample(X_train, y_train)

In [17]:
y_resampled.value_counts()

loan_status
0    56271
1    56271
Name: count, dtype: int64

In [18]:
X_train1, X_test1, y_train1, y_test1 = train_test_split(X_resampled, y_resampled, random_state=1)

### Step 2: Use the `LogisticRegression` classifier and the resampled data to fit the model and make predictions.

In [19]:
# Consolidated MLflow run for resampled (balanced) data logistic regression model
mlflow.end_run()
with mlflow.start_run(run_name="Logistic_Regression_Resampled_Data"):
    from sklearn.linear_model import LogisticRegression
    import tempfile, os

    # Train model on balanced data
    lr_resampled = LogisticRegression(solver='lbfgs', max_iter=200, random_state=1)
    lr_resampled.fit(X_train1, y_train1)

    # Predictions
    y_train1_pred = lr_resampled.predict(X_train1)
    y_test1_pred = lr_resampled.predict(X_test1)

    # Metrics
    train_accuracy = accuracy_score(y_train1, y_train1_pred)
    test_accuracy = accuracy_score(y_test1, y_test1_pred)
    train_roc_auc = roc_auc_score(y_train1, lr_resampled.predict_proba(X_train1)[:, 1])
    test_roc_auc = roc_auc_score(y_test1, lr_resampled.predict_proba(X_test1)[:, 1])

    # Classification reports
    train_report = classification_report(y_train1, y_train1_pred)
    test_report = classification_report(y_test1, y_test1_pred)

    # Confusion matrices
    train_cm = confusion_matrix(y_train1, y_train1_pred)
    test_cm = confusion_matrix(y_test1, y_test1_pred)

    # Log params
    mlflow.log_params({
        "model_type": "LogisticRegression",
        "solver": "lbfgs",
        "C": 1.0,
        "max_iter": 200,
        "random_state": 1,
        "data_type": "resampled_balanced",
        "sampling_method": "RandomOverSampler",
        "class_balance": f"healthy: {(y_train1 == 0).sum()}, high_risk: {(y_train1 == 1).sum()}",
        "training_samples": len(X_train1),
        "features": X_train1.shape[1],
        "original_imbalance_ratio": f"{(y_train == 0).sum()}:{(y_train == 1).sum()}"
    })

    # Log metrics
    mlflow.log_metrics({
        "train_accuracy": train_accuracy,
        "test_accuracy": test_accuracy,
        "train_roc_auc": train_roc_auc,
        "test_roc_auc": test_roc_auc
    })

    # Evaluation artifact
    with tempfile.NamedTemporaryFile(mode='w', suffix='.txt', delete=False) as f:
        f.write("RESAMPLED DATA MODEL EVALUATION\n")
        f.write("="*50 + "\n\n")
        f.write("TRAIN CONFUSION MATRIX:\n" + str(train_cm) + "\n\n")
        f.write("TEST CONFUSION MATRIX:\n" + str(test_cm) + "\n\n")
        f.write("TRAIN CLASSIFICATION REPORT:\n" + train_report + "\n\n")
        f.write("TEST CLASSIFICATION REPORT:\n" + test_report + "\n")
        eval_file = f.name
    mlflow.log_artifact(eval_file, artifact_path="model_evaluation")
    os.unlink(eval_file)

    # Log model
    mlflow.sklearn.log_model(lr_resampled, "logistic_regression_resampled_model")

    print("✅ Resampled data model trained & fully logged to MLflow")
    print(f"Test Accuracy: {test_accuracy:.4f} | Test ROC AUC: {test_roc_auc:.4f}")

2025/08/14 10:42:14 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/08/14 10:42:16 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/08/14 10:42:16 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

✅ Resampled data model trained & fully logged to MLflow
Test Accuracy: 0.9942 | Test ROC AUC: 0.9945

### Step 3: Evaluate the model’s performance by doing the following:

* Calculate the accuracy score of the model.

* Generate a confusion matrix.

* Print the classification report.

In [20]:
# Accuracy for resampled model logged inside consolidated MLflow run above.
print("Resampled model accuracy logged to MLflow.")

Resampled model accuracy logged to MLflow.

In [21]:
# Confusion matrices for resampled model logged as artifact in MLflow.
print("Training confusion matrix stored in MLflow artifacts.")

Training confusion matrix stored in MLflow artifacts.

In [22]:
# Testing confusion matrix for resampled model logged in MLflow artifacts.
print("Testing confusion matrix stored in MLflow artifacts.")

Testing confusion matrix stored in MLflow artifacts.

In [23]:
# Print the Training classification report for the model
training_report = classification_report(y_train1, y_train1_pred)
print(training_report)

              precision    recall  f1-score   support

           0       0.99      0.99      0.99     42165
           1       0.99      0.99      0.99     42241

    accuracy                           0.99     84406
   macro avg       0.99      0.99      0.99     84406
weighted avg       0.99      0.99      0.99     84406

In [24]:
# All metrics, reports, and artifacts for resampled model logged in consolidated MLflow run.
print("Resampled model evaluation available via mlflow ui.")

Resampled model evaluation available via mlflow ui.

### Step 4: Answer the following question

**Question:** How well does the logistic regression model, fit with oversampled data, predict both the `0` (healthy loan) and `1` (high-risk loan) labels?

**Answer:** It performs noticably better at identifying high risk loans in addition to identifying healthy loans. The overall prediction rate is consistent across precision, recall, and accuracy.

---

## Model Deployment Preparation

Now let's prepare this model for deployment by saving the trained model and creating deployment files.

In [25]:
mlflow.end_run()

# Start final MLflow run for production model deployment
with mlflow.start_run(run_name="Production_Model_Deployment"):
    import joblib, tempfile, os
    from sklearn.linear_model import LogisticRegression

    # Train on resampled (balanced) data
    final_model = LogisticRegression(solver='lbfgs', max_iter=200, random_state=1)
    final_model.fit(X_resampled, y_resampled)

    # Evaluation on original test split (real-world distribution)
    final_train_pred = final_model.predict(X_resampled)
    final_test_pred = final_model.predict(X_test1)
    train_accuracy = accuracy_score(y_resampled, final_train_pred)
    test_accuracy = accuracy_score(y_test1, final_test_pred)
    train_roc_auc = roc_auc_score(y_resampled, final_model.predict_proba(X_resampled)[:, 1])
    test_roc_auc = roc_auc_score(y_test1, final_model.predict_proba(X_test1)[:, 1])

    # Log production params
    mlflow.log_params({
        "model_type": "LogisticRegression_Production",
        "training_data": "resampled_balanced",
        "deployment_ready": True,
        "solver": "lbfgs",
        "C": 1.0,
        "max_iter": 200,
        "random_state": 1,
        "total_training_samples": len(X_resampled),
        "features": X_resampled.shape[1]
    })

    # Log metrics with unified naming
    mlflow.log_metrics({
        "train_accuracy": train_accuracy,
        "test_accuracy": test_accuracy,
        "train_roc_auc": train_roc_auc,
        "test_roc_auc": test_roc_auc
    })

    # Save traditional joblib artifacts
    joblib.dump(final_model, 'credit_risk_model.pkl')
    feature_names = X.columns.tolist()
    joblib.dump(feature_names, 'feature_names.pkl')

    # Log evaluation artifact
    with tempfile.NamedTemporaryFile(mode='w', suffix='.txt', delete=False) as f:
        f.write("PRODUCTION MODEL EVALUATION\n")
        f.write("="*50 + "\n\n")
        f.write("TRAIN ACCURACY: {:.4f}\nTEST ACCURACY: {:.4f}\n".format(train_accuracy, test_accuracy))
        f.write("TRAIN ROC AUC: {:.4f}\nTEST ROC AUC: {:.4f}\n\n".format(train_roc_auc, test_roc_auc))
        f.write("FEATURES ({}):\n".format(len(feature_names)))
        f.write("\n".join(feature_names))
        eval_file = f.name
    mlflow.log_artifact(eval_file, artifact_path="model_metadata")
    os.unlink(eval_file)

    # Register model
    model_info = mlflow.sklearn.log_model(
        final_model,
        "production_model",
        registered_model_name="CreditRiskClassifier"
    )

    print("✅ Production model saved, logged & registered in MLflow!")
    print(f"Model URI: {model_info.model_uri}")
    print(f"Test Accuracy: {test_accuracy:.4f} | Test ROC AUC: {test_roc_auc:.4f}")

2025/08/14 10:42:16 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2025/08/14 10:42:18 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/08/14 10:42:18 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

✅ Production model saved, logged & registered in MLflow!
Model URI: models:/m-e48076057fff4bcb8a771897251ab409
Test Accuracy: 0.9942 | Test ROC AUC: 0.9945

Successfully registered model 'CreditRiskClassifier'.
Created version '1' of model 'CreditRiskClassifier'.

## MLflow Experiment Tracking Summary

### 🎯 **Experiment Overview**
This project uses **MLflow** for comprehensive experiment tracking and model management:

### **📊 Tracked Experiments:**
1. **Logistic_Regression_Original_Data**: Model trained on imbalanced data
2. **Logistic_Regression_Resampled_Data**: Model trained on balanced data using RandomOverSampler
3. **Production_Model_Deployment**: Final production-ready model

### **📈 Key Metrics Tracked:**
- **Accuracy**: Training and testing accuracy
- **ROC AUC**: Area under the ROC curve
- **Precision & Recall**: For both healthy and high-risk loans
- **Class Balance**: Before and after resampling

### **🔧 Parameters Logged:**
- Model hyperparameters (solver, C, max_iter)
- Data preprocessing details
- Sampling strategy information
- Feature engineering steps

### **📁 Artifacts Stored:**
- Confusion matrices
- Classification reports
- Model files (.pkl format)
- Feature metadata

### **🚀 How to View MLflow UI (Port 8000):**
```bash
# Start MLflow UI on port 8000 (use this if 5000 is blocked)
mlflow ui --port 8000

# Then open in your browser:
http://localhost:8000
```
(Optional) If you need to access on a different host/interface:
```bash
mlflow ui --host 0.0.0.0 --port 8000
```

### **🏆 Model Registry:**
- **Model Name**: `CreditRiskClassifier`
- **Status**: Ready for production deployment
- **Version Control**: Automatic versioning of model iterations

In [27]:
# MLflow Experiment Summary and Model Comparison
print("=" * 80)
print("🎯 MLFLOW EXPERIMENT SUMMARY")
print("=" * 80)

# Get experiment information
experiment = mlflow.get_experiment_by_name("Credit_Risk_Classification_Logistic_Regression")
print(f"📊 Experiment Name: {experiment.name}")
print(f"📁 Experiment ID: {experiment.experiment_id}")
print(f"📍 Artifact Location: {experiment.artifact_location}")

# Search all runs in this experiment
runs = mlflow.search_runs(experiment_ids=[experiment.experiment_id])
print(f"\n🔍 Total Runs: {len(runs)}")

# Display run summary
print("\n📈 RUN PERFORMANCE SUMMARY:")
print("-" * 60)
for _, run in runs.iterrows():
    run_name = run['tags.mlflow.runName'] if 'tags.mlflow.runName' in run else 'Unnamed'
    test_acc = run['metrics.test_accuracy'] if 'metrics.test_accuracy' in run else 'N/A'
    test_auc = run['metrics.test_roc_auc'] if 'metrics.test_roc_auc' in run else 'N/A'
    print(f"🏃 {run_name}")
    print(f"   ✅ Test Accuracy: {test_acc}")
    print(f"   📊 ROC AUC: {test_auc}")
    print()

print("🚀 TO VIEW DETAILED RESULTS:")
print("1. Open terminal and run: mlflow ui --port 8000")
print("2. Navigate to: http://localhost:8000")
print("3. Explore experiments, compare runs, and view artifacts")

print("\n🏆 PRODUCTION MODEL:")
print("Model 'CreditRiskClassifier' registered in MLflow Model Registry")
print("Ready for deployment and monitoring!")
print("=" * 80)

================================================================================
🎯 MLFLOW EXPERIMENT SUMMARY
================================================================================
📊 Experiment Name: Credit_Risk_Classification_Logistic_Regression
📁 Experiment ID: 259187339359411637
📍 Artifact Location: file:///Users/nishaantsoni/Documents/My_Projects/Credit_Risk_Classification_using_Logistic_Regression/mlruns/259187339359411637

🔍 Total Runs: 4

📈 RUN PERFORMANCE SUMMARY:
------------------------------------------------------------
🏃 Production_Model_Deployment
   ✅ Test Accuracy: 0.9941711686096104
   📊 ROC AUC: 0.9945198451112285

🏃 Logistic_Regression_Resampled_Data
   ✅ Test Accuracy: 0.9941711686096104
   📊 ROC AUC: 0.9945368581372338

🏃 nervous-lark-803
   ✅ Test Accuracy: 0.9925711927362774
   📊 ROC AUC: 0.9938731190599486

🏃 Logistic_Regression_Original_Data
   ✅ Test Accuracy: 0.9925711927362774
   📊 ROC AUC: 0.9938731190599486

🚀 TO VIEW DETAILED RESULTS:
1. Open terminal and run: mlflow ui --port 8000
2. Navigate to: http://localhost:8000
3. Explore experiments, compare runs, and view artifacts

🏆 PRODUCTION MODEL:
Model 'CreditRiskClassifier' registered in MLflow Model Registry
Ready for deployment and monitoring!
================================================================================